working_dir_path: netprop_workflow
can_write_console_log: False
run_md: true
parent_dir_path: ../../netprop_workflow

step1_gda_retrieval:
  paths:
    input_file_path: "."
    output_csv_path:  gda_result.csv
  properties:
    retrieve_by: 'disease'
    disease_id: C0002395
    max_score: 1.0

step_vda_retrieval:
  paths:
    input_file_path: "."
    output_file_path:  vda_result.csv
  properties:
    retrieve_by: 'disease'
    disease_id: C0002395
    max_score: 1.0

step_dda_retrieval:
  paths:
    input_file_path: "."
    output_file_path:  dda_result.csv
  properties:
    retrieve_by: 'genes'
    disease_id: C0002395
    pvalue: 0.7
    limit: 10


step_ga_retrieval:
  paths:
    input_file_path: "."
    output_file_path:  ga_result.csv
  properties:
    retrieve_by: 'gene'
    gene_id: 'AD3L'
    max_dsi: 0.7

step_da_retrieval:
  paths:
    input_file_path: "."
    output_file_path:  da_result.csv
  properties:
    retrieve_by: 'disease'
    disease_id: C0002395
    max_dsi: 0.7

step_va_retrieval:
  paths:
    input_file_path: "."
    output_file_path:  va_result.csv
  properties:
    retrieve_by: 'variant'
    variant_id: C0002395
    max_dsi: 0.7

step2_parse_hippie:
  paths: 
    input_file_path1: "/home/bscuser/Escritorio/biobbs/biobb_netprop/datasets/hippie_current.txt"
    input_file_path2: "/home/bscuser/Escritorio/biobbs/biobb_netprop/datasets/hs_genes.txt"
    output_sif_path: interactome.sif
  properties:
    hippie_score: 0.2 

step3_making_nodes:
  paths:
    input_file_path1: dependency/step2_parse_hippie/output_sif_path
    input_file_path2: dependency/step1_gda_retrieval/output_csv_path
    input_file_dataset: "/home/bscuser/Escritorio/biobbs/biobb_netprop/datasets/"
    output_sif_path: nodes.sif
  properties:
    curated: False
    scoring_mode: dis

step4_call_guild:
  paths:
    input_file_path2: dependency/step2_parse_hippie/output_sif_path
    input_file_path1: dependency/step3_making_nodes/output_sif_path
    input_netprop_dir: "/home/bscuser/Escritorio/biobbs/biobb_netprop/biobb_netprop/disc4all-data-fra/guild/"
    output_path:  output_netscore
  properties:
    algorithm: s
